// Generated by https://pagedraw.io/pages/7923
import * as React from 'react';
// tslint:disable



import './checkbox.css';

export default class PagedrawnComponent extends React.Component<any, any> {
  render() {
    return (
      <div className="pd-onhover-parent checkbox">
          { (this.props.state === "unchecked") ?
              <div className="checkbox-unchecked-1">
                  <div className="checkbox-0-0-0">
                      <div className="checkbox-rectangle-4" /> 
                  </div>
              </div>
          : null}
          <div className="pd-onhover checkbox-_hover-2">
              <div className="checkbox-1-0">
                  <div className="checkbox-rectangle-3" /> 
              </div>
          </div>
          { (this.props.state === "checked") ?
              <div className="checkbox-checked-4">
                  <div className="checkbox-2-0-0">
                      <div className="checkbox-rectangle-5">
                          <div className="checkbox-2-0-0-0-0">
                              <div className="checkbox-text_2">{"✔"}</div>
                          </div>
                      </div>
                  </div>
              </div>
          : null}
      </div>
    );
  }
}