// Generated by https://pagedraw.io/pages/7923
import * as React from 'react';
// tslint:disable


import Task_item from './task_item';
import './homepage.css';

export default class PagedrawnComponent extends React.Component<any, any> {
  render() {
    return (
      <div className="homepage-homepage-7">
          <div className="homepage-0">
              <div className="homepage-0-0" /> 
              <div className="homepage-header-9">
                  {"Seriously the best TODO list in the world.™️"}
              </div>
              <div className="homepage-0-2" /> 
          </div>
          <div className="homepage-1">
              <div className="homepage-1-0" /> 
              <div className="homepage-rectangle_4">
                  <div className="homepage-1-1-0">
                      <div className="homepage-1-1-0-0">
                          { this.props.items.map((elem, i) => {
                              return <div key={i} className="homepage-rectangle_3">
                                  <div className="homepage-1-1-0-0-0-0-0">
                                      <div className="homepage-task_item_instance-9">
                                          <Task_item state={elem.state} text={elem.text} /> 
                                      </div>
                                  </div>
                              </div>;
                          }) }
                      </div>
                  </div>
              </div>
              <div className="homepage-1-2" /> 
          </div>
          <div className="homepage-2" /> 
      </div>
    );
  }
}