// Generated by https://pagedraw.io/pages/7923
import * as React from 'react';
// tslint:disable


import Checkbox from './checkbox';
import './task_item.css';

export default class PagedrawnComponent extends React.Component<any, any> {
  render() {
    return (
      <div className="pd-onhover-parent pd-onactive-parent task_item">
          { (('default') === "default") ?
              <div className="task_item-default-5">
                  <div className="task_item-0-0-0">
                      <div className="task_item-rectangle_2">
                          <div className="task_item-0-0-0-0-0">
                              <div className="task_item-checkbox-1">
                                  <Checkbox state={this.props.state} /> 
                              </div>
                              <div className="task_item-text-1">{ this.props.text }</div>
                              <div className="task_item-0-0-0-0-0-2" /> 
                          </div>
                      </div>
                  </div>
              </div>
          : null}
          <div className="pd-onhover task_item-_hover-8">
              <div className="task_item-1-0">
                  <div className="task_item-rectangle_2-0">
                      <div className="task_item-1-0-0-0">
                          <div className="task_item-checkbox-9">
                              <Checkbox state={this.props.state} /> 
                          </div>
                          <div className="task_item-text-8">{ this.props.text }</div>
                          <div className="task_item-1-0-0-0-2" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="pd-onactive task_item-_active-8">
              <div className="task_item-2-0">
                  <div className="task_item-rectangle_2-3">
                      <div className="task_item-2-0-0-0">
                          <div className="task_item-checkbox-0">
                              <Checkbox state={this.props.state} /> 
                          </div>
                          <div className="task_item-text-85">
                              { this.props.text }
                          </div>
                          <div className="task_item-2-0-0-0-2" /> 
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
}